# Generated by Django 4.1.1 on 2022-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
